# Generated by Django 5.2.7 on 2025-11-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_task_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
