# Generated by Django 5.2.7 on 2025-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='developer',
            field=models.BooleanField(default=False),
        ),
    ]
