# Generated by Django 5.2.7 on 2025-11-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_developer',
        ),
    ]
