# Generated by Django 5.2.7 on 2025-11-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_is_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
