# Generated by Django 5.2.7 on 2025-11-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_role',
            field=models.CharField(choices=[('None', 'None'), ('Leader', 'Leader'), ('Mod', 'Mod'), ('Member', 'Member')], default='None', max_length=16),
        ),
    ]
