# Generated by Django 5.2.8 on 2026-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_team_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_see_work_hours',
            field=models.BooleanField(default=False),
        ),
    ]
