# Generated by Django 5.2.5 on 2025-09-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_filter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filter',
            new_name='V2RayConfig',
        ),
    ]
