# Generated by Django 5.2.5 on 2025-09-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_v2ray_access',
            field=models.BooleanField(default=True, help_text='User can access V2Ray page and features'),
        ),
    ]
