# Generated by Django 5.2.5 on 2025-09-18 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_userprofile_has_v2ray_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='permanent_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permanent Note',
                'verbose_name_plural': 'Permanent Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]