# Generated by Django 5.2.5 on 2025-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_events_json',
            field=models.TextField(blank=True, help_text="JSON representation of user's daily calendar events", null=True),
        ),
    ]
