# Generated by Django 5.2.5 on 2025-10-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='category',
            field=models.CharField(default='personal', max_length=50),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('gray', 'Gray')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
