# Generated by Django 5.2.5 on 2025-10-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_dailygoal_category_dailygoal_color_dailygoal_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='target_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
