# Generated by Django 5.2.7 on 2025-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_assignedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
