# Generated by Django 5.2.7 on 2025-11-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
