# Generated by Django 5.2.7 on 2025-11-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_telegramconversationstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramConversationState',
        ),
        migrations.AddField(
            model_name='telegram',
            name='bot_status',
            field=models.CharField(choices=[('start', 'Start'), ('restart', 'Restart'), ('pause', 'Pause'), ('idle', 'Idle')], default='idle', max_length=20),
        ),
    ]
