# Generated by Django 5.2.8 on 2025-12-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_delete_telegramconversationstate_telegram_bot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='send_dollar_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegram',
            name='send_gold_price',
            field=models.BooleanField(default=False),
        ),
    ]
