# Generated by Django 5.2.8 on 2025-12-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_telegram_send_dollar_price_telegram_send_gold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='dollar_price_cmd',
            field=models.CharField(default='/dollar', max_length=50),
        ),
        migrations.AddField(
            model_name='telegram',
            name='gold_price_cmd',
            field=models.CharField(default='/gold', max_length=50),
        ),
    ]
