# Generated by Django 5.2.8 on 2025-12-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_telegram_send_task_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='google_sheets_auto_sync_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic sync with Google Sheets'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='google_sheets_sync_interval',
            field=models.IntegerField(default=10, help_text='Google Sheets sync interval in hours'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='sae_automation_interval',
            field=models.IntegerField(default=5, help_text='Automation interval in hours for SAE data sync'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='sae_data_enabled',
            field=models.BooleanField(default=False, help_text='Enable saving website data to Telegram'),
        ),
    ]
