# Generated by Django 5.2.8 on 2025-12-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_add_status_to_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='send_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegram',
            name='send_submissions',
            field=models.BooleanField(default=False),
        ),
    ]
