# Generated by Django 5.2.8 on 2025-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_telegram_send_reports_telegram_send_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='send_team',
            field=models.BooleanField(default=False),
        ),
    ]
