# Generated by Django 5.2.8 on 2025-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_configfile_is_public_configfile_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfile',
            name='target_role',
            field=models.CharField(blank=True, help_text='Target role (e.g., Leader, Mod, Member)', max_length=50, null=True),
        ),
    ]
