# Generated by Django 5.2.8 on 2025-12-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
    ]
