# Generated by Django 5.2.8 on 2025-12-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_chatmessage_image_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
