# Generated by Django 5.2.8 on 2026-01-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_notification_is_saved'),
        ('tickets', '0043_workinghours'),
    ]

    operations = [
    ]
