# Generated by Django 5.2.8 on 2026-01-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_alter_chatroom_user1_alter_chatroom_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notepad_content',
            field=models.TextField(blank=True, help_text="User's personal notepad content", null=True),
        ),
    ]
