# Generated by Django 5.2.8 on 2026-02-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_chatmessage_saved_fields'),
        ('tickets', '0049_remove_task'),
    ]

    operations = [
    ]
