# Generated by Django 5.2.8 on 2026-02-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0050_merge_0049_chatmessage_saved_fields_0049_remove_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='afternoon_partial_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='afternoon_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('absent', 'Absent'), ('partial', 'Partial')], default='absent', max_length=10),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='morning_partial_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='morning_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('absent', 'Absent'), ('partial', 'Partial')], default='absent', max_length=10),
        ),
    ]
