# Generated by Django 5.2.8 on 2026-01-26 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Board', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='structure_joined_boards', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_owned_boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('source_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('target_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('animated', models.BooleanField(default=False)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(default='default', max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='structure.board')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('data', models.JSONField(default=dict)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('measured_width', models.FloatField(blank=True, null=True)),
                ('measured_height', models.FloatField(blank=True, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('dragging', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='structure.board')),
            ],
        ),
    ]
